openapi: 3.0.2
info:
  title: TerpNET Historical Data
  description: REST API to get the historical data for TerpNET
  version: 1.1.1
servers:
  - url: https://api.terp.network/
    description: TerpNET Historical Data
paths:
TBD